In [237]:
import numpy as np
import itertools

In [238]:
# Порождающая матрица линейного кода (7, 4, 3)
def generative_matrix(x, k):
    return np.hstack((np.eye(k, dtype=int), x))

# Проверочная матрица на основе порождающей 
def check_matrix(x, n, k):
    return np.vstack((x, np.eye(n - k, dtype=int)))

# Таблица синдромов для однократных ошибок
def get_syndromes(H):
    return {str(row): [i] for i, row in enumerate(H)}

# Таблица синдромов для однократных и двукратных ошибок
def get_syndromes_2(H, n):
    syndromes = {str(row): [i] for i, row in enumerate(H)}
    mistakes = np.eye(n, dtype=int)

    for comb in itertools.combinations(range(n), 2):
        mistake_vector = (mistakes[comb[0]] + mistakes[comb[1]]) @ H % 2
        syndromes[str(mistake_vector)] = comb

    return syndromes


# Исправление однократной ошибки
def mistake_correct(syndromes, syndrom, word):
    k = syndromes.get(str(syndrom))
    if k is None:
        print("Синдром отсутствует", '\n')
    else:
        word[k] += 1
        word[k] %= 2
    return word

# Исправление двукратной ошибки
def mistake_correct_2(syndromes, syndrom, word):
    k, d = syndromes.get(str(syndrom), (-1, -1))
    if k == -1:
        print("Синдром отсутствует")
    if k != -1:
        word[k] += 1
        word[k] %= 2
        if d != -1:
            word[d] += 1
            word[d] %= 2
    return word

In [239]:
first = np.array([[1, 1, 1],
                           [1, 1, 0],
                           [1, 0, 1],
                           [0, 1, 1]])

n = 7
k = 4
G = generative_matrix(first, k)
print("G (7,4,3): ", '\n', G, '\n')
H = check_matrix(first, n, k)
print("H: ", '\n', H, '\n')
table_syndromes = get_syndromes(H)
print("Синдромы для однократных ошибок:", table_syndromes, sep='\n')

E = np.eye(n, dtype=int)
true_word = [1, 0, 1, 0]
print("\nИсходное слово: ", np.array(true_word))
output_word = np.array(true_word) @ G % 2
print("Отправленное слово: ", output_word)
one_error_word = (output_word + E[5]) % 2
print("Слово с одной ошибкой: ", one_error_word)
syndrom = one_error_word @ H % 2
print("Синдром: ", syndrom)
corrected_word = mistake_correct(table_syndromes, syndrom, one_error_word)
print("Слово после исправления ошибки: ", corrected_word)
check_corrected_word = corrected_word @ H % 2
print("Проверка исправленного слова: ", check_corrected_word, '\n')

E = np.eye(n, dtype=int)
true_word = [1, 0, 1, 0]
print("\nИсходное слово: ", np.array(true_word))
output_word = np.array(true_word) @ G % 2
print("Отправленное слово: ", output_word)
two_errors_word = (output_word + E[2] + E[5]) % 2
print("Слово с двумя ошибками: ", two_errors_word)
syndrom = two_errors_word @ H % 2
print("Синдром: ", syndrom)
corrected_word = mistake_correct(table_syndromes, syndrom, two_errors_word)
print("Слово после исправления ошибки: ", corrected_word)
check_corrected_word = corrected_word @ H % 2
print("Проверка исправленного слова: ", check_corrected_word, '\n')

G (7,4,3):  
 [[1 0 0 0 1 1 1]
 [0 1 0 0 1 1 0]
 [0 0 1 0 1 0 1]
 [0 0 0 1 0 1 1]] 

H:  
 [[1 1 1]
 [1 1 0]
 [1 0 1]
 [0 1 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]] 

Синдромы для однократных ошибок:
{'[1 1 1]': [0], '[1 1 0]': [1], '[1 0 1]': [2], '[0 1 1]': [3], '[1 0 0]': [4], '[0 1 0]': [5], '[0 0 1]': [6]}

Исходное слово:  [1 0 1 0]
Отправленное слово:  [1 0 1 0 0 1 0]
Слово с одной ошибкой:  [1 0 1 0 0 0 0]
Синдром:  [0 1 0]
Слово после исправления ошибки:  [1 0 1 0 0 1 0]
Проверка исправленного слова:  [0 0 0] 


Исходное слово:  [1 0 1 0]
Отправленное слово:  [1 0 1 0 0 1 0]
Слово с двумя ошибками:  [1 0 0 0 0 0 0]
Синдром:  [1 1 1]
Слово после исправления ошибки:  [0 0 0 0 0 0 0]
Проверка исправленного слова:  [0 0 0] 



In [240]:
second = np.array([[0, 1, 1, 1, 1, 0, 0],
                            [1, 1, 0, 1, 1, 1, 1],
                            [0, 0, 1, 1, 0, 1, 1],
                            [1, 0, 1, 0, 1, 1, 0]])

n = 11
k = 4
G = generative_matrix(second, k)
print("Порождающая матрица G (11,4,5):", '\n', G, '\n')

H = check_matrix(second, n, k)
print("Проверочная матрица H", '\n', H, '\n')

table_syndromes = get_syndromes_2(H, n)
print("Таблица синдромов:", table_syndromes, sep='\n')

E = np.eye(n, dtype=int)
true_word = [1, 0, 1, 0]
print("\nИсходное слово: ", np.array(true_word))
output_word = np.array(true_word) @ G % 2
print("Отправленное слово: ", output_word)
one_error_word = (output_word + E[5]) % 2
print("Слово с одной ошибкой: ", one_error_word)
syndrom = one_error_word @ H % 2
print("Синдром: ", syndrom)
corrected_word = mistake_correct(table_syndromes, syndrom, one_error_word)
print("Слово после исправления ошибки: ", corrected_word)
check_corrected_word = corrected_word @ H % 2
print("Проверка исправленного слова: ", check_corrected_word, '\n')

E = np.eye(n, dtype=int)
true_word = [1, 0, 1, 0]
print("\nИсходное слово: ", np.array(true_word))
output_word = np.array(true_word) @ G % 2
print("Отправленное слово: ", output_word)
two_errors_word = (output_word + E[2] + E[5]) % 2
print("Слово с двумя ошибками: ", two_errors_word)
syndrom = two_errors_word @ H % 2
print("Синдром: ", syndrom)
corrected_word = mistake_correct_2(table_syndromes, syndrom, two_errors_word)
print("Слово после исправления: ", corrected_word)
check_corrected_word = corrected_word @ H % 2
print("Проверка исправленного слова: ", check_corrected_word, '\n')

E = np.eye(n, dtype=int)
true_word = [0, 1, 1, 0]
print("\nИсходное слово: ", np.array(true_word))
output_word = np.array(true_word) @ G % 2
print("Отправленное слово: ", output_word)
three_errors_word = (output_word + E[1] + E[3] + E[4]) % 2
print("Слово с тремя ошибками: ", three_errors_word)
syndrom = three_errors_word @ H % 2
print("Синдром: ", syndrom)
corrected_word = mistake_correct_2(table_syndromes, syndrom, three_errors_word)
print("Слово после исправления отличается от отправленного: ", corrected_word)
check_corrected_word = corrected_word @ H % 2
print("Проверка исправленного слова: ", check_corrected_word, '\n')

Порождающая матрица G (11,4,5): 
 [[1 0 0 0 0 1 1 1 1 0 0]
 [0 1 0 0 1 1 0 1 1 1 1]
 [0 0 1 0 0 0 1 1 0 1 1]
 [0 0 0 1 1 0 1 0 1 1 0]] 

Проверочная матрица H 
 [[0 1 1 1 1 0 0]
 [1 1 0 1 1 1 1]
 [0 0 1 1 0 1 1]
 [1 0 1 0 1 1 0]
 [1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1]] 

Таблица синдромов:
{'[0 1 1 1 1 0 0]': [0], '[1 1 0 1 1 1 1]': [1], '[0 0 1 1 0 1 1]': [2], '[1 0 1 0 1 1 0]': [3], '[1 0 0 0 0 0 0]': [4], '[0 1 0 0 0 0 0]': [5], '[0 0 1 0 0 0 0]': [6], '[0 0 0 1 0 0 0]': [7], '[0 0 0 0 1 0 0]': [8], '[0 0 0 0 0 1 0]': [9], '[0 0 0 0 0 0 1]': [10], '[1 0 1 0 0 1 1]': (0, 1), '[0 1 0 0 1 1 1]': (0, 2), '[1 1 0 1 0 1 0]': (0, 3), '[1 1 1 1 1 0 0]': (0, 4), '[0 0 1 1 1 0 0]': (0, 5), '[0 1 0 1 1 0 0]': (0, 6), '[0 1 1 0 1 0 0]': (0, 7), '[0 1 1 1 0 0 0]': (0, 8), '[0 1 1 1 1 1 0]': (0, 9), '[0 1 1 1 1 0 1]': (0, 10), '[1 1 1 0 1 0 0]': (1, 2), '[0 1 1 1 0 0 1]': (1, 3), '[0 1 0 1 1 1 1]': (1, 4), '[1 0 0 1 1 