In [1]:
import random
import numpy as np

In [2]:
# Таблица синдромов
def get_syndromes(H):
    return {str(row): [i] for i, row in enumerate(H)}

# Исправление ошибки
def encode(syndromes, syndrom, word):
    k = syndromes.get(str(syndrom))
    if k is None:
        print("Синдром отсутствует", '\n')
    else:
        word[k] += 1
        word[k] %= 2
    return word

# Порождающая и проверочная матрицы кода Хэмминга
def hemming_matrix(r):
    t = np.array([[int(el) for el in format(i, f'0{r}b')] for i in range(2 ** r)])
    t = t[np.sum(t, axis=1) > 1]
    G = np.hstack((np.eye(len(t), dtype=int), t))
    H = np.vstack((t, np.eye(r, dtype=int)))
    
    return G, H

# Порождающая и проверочная матрицы расширенного кода Хэмминга
def hemming_extended_matrix(r):
    G, H = hemming_matrix(r)
    H = np.append(H, [np.zeros(len(H.T), dtype=int)], axis=0)
    H = np.append(H, np.ones((len(H), 1), dtype=int), axis=1)
    G = np.append(G, np.zeros((len(G), 1), dtype=int), axis=1)
    for i in range(len(G)):
        if sum(G[i]) % 2 == 1:
            G[i][len(G.T) - 1] = 1
    return G, H

# Исследование кода Хэмминга на ошибки
def check_mistakes_hemming(G, H, table_syndromes, r, extend):
    e = np.eye(G.shape[1], dtype=int)
    x = np.random.randint(0, 2, 2**r - r - 1)
    word = x @ G % 2
    if extend:
        number_mistake = 5
    else:
        number_mistake = 4
    for step in range(1, number_mistake):
        print("\nИсходное слово: ", x)
        print("Отправленное слово: ", word)
        index = random.sample(range(0, e.shape[0]), step)
        word_with_mistake = word
        for i in index:
            word_with_mistake = (word_with_mistake + e[i]) % 2
        print("Слово с", step, "кратной ошибкой: ", word_with_mistake)
        syndrom = word_with_mistake @ H % 2
        print("Синдром: ", syndrom)
        corrected_word = encode(table_syndromes, syndrom, word_with_mistake)
        print("Слово после исправления ошибки: ", corrected_word)
        check_corrected_word = corrected_word @ H % 2
        print("Проверка исправленного слова: ", check_corrected_word, '\n')

# Исследование кода Хэмминга
def hemming():
    for r in range(2, 5):
        print("Хемминг. Параметр r = ", r, '\n')
        g, h = hemming_matrix(r)
        table_syndromes = get_syndromes(h)
        print("G:", g, sep='\n')
        print("H:", h, sep='\n')
        print("Таблица синдромов: ", table_syndromes)
        check_mistakes_hemming(g, h, table_syndromes, r, False)

# Исследование расширенного кода Хэмминга
def hemming_extended():
    for r in range(2, 5):
        print("Расширенный Хемминг. Параметр r = ", r,'\n')
        g, h = hemming_extended_matrix(r)
        table_syndromes = get_syndromes(h)
        print("G:", g, sep='\n')
        print("H:", h, sep='\n')
        print("Таблица синдромов: ", table_syndromes)
        check_mistakes_hemming(g, h, table_syndromes, r, True)

In [3]:
hemming()
hemming_extended()

Хемминг. Параметр r =  2 

G:
[[1 1 1]]
H:
[[1 1]
 [1 0]
 [0 1]]
Таблица синдромов:  {'[1 1]': [0], '[1 0]': [1], '[0 1]': [2]}

Исходное слово:  [0]
Отправленное слово:  [0 0 0]
Слово с 1 кратной ошибкой:  [0 0 1]
Синдром:  [0 1]
Слово после исправления ошибки:  [0 0 0]
Проверка исправленного слова:  [0 0] 


Исходное слово:  [0]
Отправленное слово:  [0 0 0]
Слово с 2 кратной ошибкой:  [1 0 1]
Синдром:  [1 0]
Слово после исправления ошибки:  [1 1 1]
Проверка исправленного слова:  [0 0] 


Исходное слово:  [0]
Отправленное слово:  [0 0 0]
Слово с 3 кратной ошибкой:  [1 1 1]
Синдром:  [0 0]
Синдром отсутствует 

Слово после исправления ошибки:  [1 1 1]
Проверка исправленного слова:  [0 0] 

Хемминг. Параметр r =  3 

G:
[[1 0 0 0 0 1 1]
 [0 1 0 0 1 0 1]
 [0 0 1 0 1 1 0]
 [0 0 0 1 1 1 1]]
H:
[[0 1 1]
 [1 0 1]
 [1 1 0]
 [1 1 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]]
Таблица синдромов:  {'[0 1 1]': [0], '[1 0 1]': [1], '[1 1 0]': [2], '[1 1 1]': [3], '[1 0 0]': [4], '[0 1 0]': [5], '[0 0 1]': [6]}

И